version: "3.9"

services:
  app:
    container_name: spotify-stats
    image: spotify-stats
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}" 